### ISSUE TITLE
Pipelines functionality should support submission-time "swap" of Docker images

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#34] opened 2021-05-20 17:15 UTC
Currently, a component spec may make itself unusable in "public" workspace by pointing to a Docker image in a tightly controlled ACR, e.g.:

```yaml
environment:
  docker:
    image: somesupersecretfeed.azurecr.io/some/image/path:tag
```

This library should consider exposing a configuration value (or, potentially, read this information from AAD tenant?) on which it will re-write the component spec files _before_ they're loaded. The users could, e.g., configure a default "public" base image / image(s), potentially indexed by OS and CPU vs. GPU. Alternatively, the library could come with a default set of "public" images, which are configurable / overrideable.

More design work is needed!

**Comment by dkmiller** [comment] 2021-06-07 17:15
The Polymer team now has an MSIT-tenant ACR that they're connecting with MyData workspaces. While the base URL and (first part) of the image path are different, the contents are identical.

That makes this functionality a bit more valuable.

**Comment by fuhuifang** [comment] 2021-06-09 19:45
This seems to be a duplicate of #43 .

**Closed by fuhuifang** 2021-06-09 19:45 UTC
Labels: enhancement, shrike.pipeline
